### ISSUE TITLE
Readd fix (in a more elegant way) for right side panel in order not to be clear when updating the favourite

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/d2-analysis#13]
Oslo said this:
`if (layout.interpretations)` crashed when the user clicks favoritemenu -> new
because setState without params is meant to be "reset"
so layout was undefined
now `addAndUpdateFavoritePanel` and `addAndUpdateInterpretationsPanel` are being run without params, which is intended, so that the interpretations panels are reset

and fix it with this https://github.com/dhis2/d2-analysis/commit/2e69a8e4d7e5ba56402b1f5bae2f7479e88a79ea

but actually we want to readd it in a more elegant way

@tokland This targets 2.25

**Comment by tokland** [comment]
Ok, now I see how it works. It's definitely not a trivial feature keeping that info; when there is any update, the state of the favorite in InstanceManager is cleared. Trying to keep the info buy not reloading the view won't work, any action the user performs later will fail, no IDs to work with. The only workaround I can think has been keeping explicitly some of the attributes on the updates (when `InstanceManager.prototype.getReport` is called without `layout`).

I've uploaded fix/eastregion-keep-info-on-updates but should not be merged yet. It works for what I've seen, but let me do some more testing tomorrow.
