### ISSUE TITLE
Integrate d2-ui-rich-text in PT/DV/ER/EV

### ISSUE THREAD

**Issue by tokland** [EyeSeeTea/d2-analysis#29]
https://jira.dhis2.org/browse/DHIS2-5492

https://github.com/dhis2/d2-ui/blob/master/examples/create-react-app/src/components/rich-text.js

**Comment by adrianq** [comment]
duplicate of https://waffle.io/EyeSeeTea/dhis2-core/cards/5c388037c08101030a85a87a ?
